---
name: Ted run for python migration

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ted run
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TED run
        uses: OpenGuidou/ted@v0.11
        env:
          OPENAI_API_VERSION: ${{ secrets.OPENAI_API_VERSION }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          EMBEDDING_DEPLOYMENT_NAME: ${{ secrets.EMBEDDING_DEPLOYMENT_NAME }}
        with:
          ted-flavor: python2-3
          github_repository: ${{ github.repository }}
          github_token: ${{ github.token }}
          branch: ${{ github.ref_name }}