---
name: Ted run for python migration

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ted run
    steps:
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: TED run
        uses: OpenGuidou/ted@v0.8
        with:
          git-repo: "${{github.repository}}"
          ted-flavor: unit-tests
